# SmartFallMM Dataset
# 51 subjects, 30Hz smartwatch, young + old
dataset: smartfallmm

subjects: [2,3,4,5,6,7,9,10,11,13,14,15,16,17,18,19,21,22,23,25,26,29,30,31,32,34,35,36,37,38,39,43,44,45,46,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63]
validation_subjects: [48, 57]
train_only_subjects: [2,3,4,5,6,7,9,10,11,13,14,15,16,17,18,19,21,22,23,25,26,29,30,32,35,39,59]

dataset_args:
  mode: sliding_window
  max_length: 128
  task: fd
  modalities: [accelerometer, gyroscope]
  age_group: [young, old]
  sensors: [watch]
  stride: 32
  use_skeleton: false
  enable_class_aware_stride: true
  fall_stride: 16
  adl_stride: 64
  enable_simple_truncation: true
  max_truncation_diff: 50
  discard_mismatched_modalities: false
  length_sensitive_modalities: [accelerometer, gyroscope]

feeder: Feeder.Make_Dataset.UTD_mm
