# Raw Accelerometer Optimal Config
# 4 channels: [smv, ax, ay, az]
# embed_dim: 64, loss_type: focal, normalize all

model: Models.transformer.TransModel
dataset: smartfallmm

subjects: [2,3,4,5,6,7,9,10,11,13,14,15,16,17,18,19,21,22,23,25,26,29,30,31,32,34,35,36,37,38,39,43,44,45,46,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63]
validation_subjects: [48, 57]
train_only_subjects: [2,3,4,5,6,7,9,10,11,13,14,15,16,17,18,19,21,22,23,25,26,29,30,32,35,39,59]

model_args:
  acc_frames: 128
  acc_coords: 4
  num_classes: 1
  num_heads: 4
  num_layer: 2
  embed_dim: 64
  dropout: 0.5
  activation: relu
  norm_first: True

dataset_args:
  mode: sliding_window
  max_length: 128
  task: fd
  modalities: [accelerometer]
  age_group: [young,old]
  sensors: [watch]
  stride: 32
  use_skeleton: False
  loss_type: focal

  enable_normalization: True
  normalize_modalities: all
  enable_filtering: False
  enable_motion_filtering: False

  enable_class_aware_stride: True
  fall_stride: 16
  adl_stride: 64

  include_smv: True

  enable_kalman_fusion: False

batch_size: 64
test_batch_size: 64
val_batch_size: 64
num_epoch: 80

feeder: Feeder.Make_Dataset.UTD_mm
train_feeder_args:
  batch_size: 64
val_feeder_args:
  batch_size: 64
test_feeder_args:
  batch_size: 64

seed: 2
optimizer: adamw
base_lr: 0.001
weight_decay: 0.001
